// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using Microsoft.EntityFrameworkCore;

namespace LoadDWHVentas.Data.Models;

public partial class DWHNorthwindOrdersContext : DbContext
{
    public DWHNorthwindOrdersContext(DbContextOptions<DWHNorthwindOrdersContext> options)
        : base(options)
    {
    }
    

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}