// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDWHVentas.Models.Models;

public partial class VwVenta
{
    public string CustomerID { get; set; }

    public string CustomerName { get; set; }

    public int employeeId { get; set; }

    public string EmployeeName { get; set; }

    public int ShipperID { get; set; }

    public string CompanyName { get; set; }

    public string Country { get; set; }

    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public int? DateKey { get; set; }

    public int? Year { get; set; }

    public int? Month { get; set; }

    public decimal? TotalSales { get; set; }

    public int? Quantity { get; set; }
}